config/routes.rb
XTick::Application.routes.draw do

  root 'tickets#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :staffs, except: [:destroy]

  post '/', to: 'search#search'

  resources :tickets, except: [:show] do
    resources :ticket_histories, except: [:show, :destroy]
  end

  get 'ticket/:customer_link', to: 'ticket_histories#customer_link',  as: 'customer_link'

end

app/models/staff.rb
class Staff < ActiveRecord::Base

  belongs_to :user

  has_many :ticket_histories
  has_many :tickets, through: :ticket_histories


  scope :approved, -> { where(approved: true) }

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  def index
    @staffs = Staff.all
  end

  def show
  end

  def edit
  end

  def update
    is_approved = staff_params[:approved]=='1'
    XTickMailer.user_access_change(@staff, is_approved).deliver
    return redirect_to staffs_path, notice: 'Profile was successfully updated.' if @staff.update(staff_params)
    render action: 'edit'
  end

  private
  def set_staff
    @staff = Staff.find(params[:id])
  end

  def staff_params
    params.require(:staff).permit(:name, :approved)
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.haml
= form_for @staff, html: { class: 'form-horizontal' } do |f|
  .control-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'text_field'
  .control-group
    = f.label :approved, class: 'control-label'
    .controls
      %div.make-switch
        = f.check_box :approved
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), staffs_path, class: 'btn'

app/views/staffs/edit.html.haml
- model_class = Staff
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/staffs/index.html.haml
- model_class = Staff
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize

- if user_signed_in_and_approved?
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:name)
        %th= 'Email'
        %th= model_class.human_attribute_name(:created_at)
        %th= model_class.human_attribute_name(:updated_at)
        %th= model_class.human_attribute_name(:approved)
        %th=t '.actions', default: t('helpers.actions')
    %tbody
      - @staffs.each do |staff|
        %tr
          %td= staff.name
          %td= staff.user.email
          %td=l staff.created_at
          %td=l staff.updated_at
          %td
            - if staff.approved
              %span.badge.badge-success on
            - else
              %span.badge.badge-important off
          %td
            = link_to t('.edit', default: t('helpers.links.edit')), edit_staff_path(staff), class: 'btn btn-primary'

app/views/staffs/new.html.haml
- model_class = Staff
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/staffs/show.html.haml
- model_class = Staff
.page-header
  %h1=t '.title', default: 'Profile'

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @staff.name
%p
  %strong= 'Email:'
  %br
  = @staff.user.email

.form-actions
  = link_to t('.back', default: t('helpers.links.back')), staffs_path, class: 'btn'
  = link_to t('.edit', default: t('helpers.links.edit')), edit_staff_path(@staff), class: 'btn btn-primary'