config/routes.rb
XTick::Application.routes.draw do

  root 'tickets#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :staffs, except: [:destroy]

  post '/', to: 'search#search'

  resources :tickets, except: [:show] do
    resources :ticket_histories, except: [:show, :destroy]
  end

  get 'ticket/:customer_link', to: 'ticket_histories#customer_link',  as: 'customer_link'

end

app/models/ticket_history.rb
class TicketHistory < ActiveRecord::Base

  belongs_to :staff
  belongs_to :ticket

  accepts_nested_attributes_for :ticket

  validates :resolution, :staff, :state, :ticket, presence: true
  validates :resolution, length: { minimum: 3,  maximum: 250 }

  def set_staff(user)
    self.staff = user.staff
  end

  def set_ticket(ticket)
    ticket.state = self.state
    self.ticket = ticket
  end

  def update_with_state(params)
    self.ticket.state = params[:state]
    self.update params
    self.save
  end

end

app/controllers/ticket_histories_controller.rb
class TicketHistoriesController < ApplicationController
  before_action :set_ticket_history, only: [:edit, :update]
  before_action :set_ticket, except: [:customer_link]

  before_filter :authenticate_user!, except: [:customer_link]

  def index
    @ticket_histories = @ticket.ticket_histories
  end

  def new
    @ticket_history = TicketHistory.new
    @ticket_history.set_staff current_user
  end

  def edit

  end

  def create
    @ticket_history = TicketHistory.new(ticket_history_params)
    @ticket_history.set_ticket @ticket

    XTickMailer.ticket_history_created(@ticket_history).deliver
    return redirect_to tickets_path, notice: 'Ticket history was successfully created.' if  @ticket_history.save
    render action: 'new'
  end

  def update
    return redirect_to tickets_path, notice: 'Ticket history was successfully updated.' if @ticket_history.update_with_state(ticket_history_params)
    render action: 'edit'
  end


  def customer_link
    @ticket = Ticket.get_by_unique_customer_link(params[:customer_link])

    return redirect_to tickets_path if @ticket.nil?
    @ticket_histories = @ticket.ticket_histories
    render 'ticket_histories/index'
  end

  private
  def set_ticket_history
    @ticket_history = TicketHistory.find(params[:id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def ticket_history_params
    params.require(:ticket_history).permit(:state, :resolution, :staff_id)
  end
end

app/helpers/ticket_histories_helper.rb
module TicketHistoriesHelper
end

app/views/ticket_histories/_form.html.haml
= form_for [@ticket,@ticket_history], html: { class: 'form-horizontal' } do |f|
  .control-group
    = f.label :staff, class: 'control-label'
    .controls
      = f.collection_select(:staff_id, Staff.approved, :id, :name)
  .control-group
    = f.label :state, class: 'control-label'
    .controls
      = f.select :state, Ticket::State.hash_values.values, class: 'select optional'
  .control-group
    = f.label :resolution, class: 'control-label'
    .controls
      = f.text_area :resolution, class: 'text_area'
  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), ticket_ticket_histories_path(@ticket), class: 'btn'

app/views/ticket_histories/edit.html.haml
- model_class = TicketHistory
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/ticket_histories/index.html.haml
- model_class = TicketHistory
.page-header
  %h1=t '.title', default:  model_class.model_name.human.pluralize.titleize

- primary_model_class = Ticket
%p
  %strong= primary_model_class.human_attribute_name(:subject) + ':'
  %br
  = @ticket.subject
%p
  %strong= primary_model_class.human_attribute_name(:body) + ':'
  %br
  = @ticket.body
%p
  %strong= 'Customer: '
  %br
  = @ticket.customer.name + '; email:' + @ticket.customer.email


%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:staff_id)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:resolution)
      %th= model_class.human_attribute_name(:created_at)
      - if user_signed_in_and_approved?
        %th=t '.actions', default: t('helpers.actions')
  %tbody
    - @ticket_histories.each do |ticket_history|
      %tr
        %td= ticket_history.staff_id
        %td= ticket_history.state
        %td= ticket_history.resolution
        %td=l ticket_history.created_at
        - if user_signed_in_and_approved?
          %td
            = link_to t('.edit', default: t('helpers.links.edit')), edit_ticket_ticket_history_path(@ticket,ticket_history), class: 'btn'

- if user_signed_in_and_approved?
  = link_to t('.new', default: t('helpers.links.new')), new_ticket_ticket_history_path(@ticket), class: 'btn btn-primary'

app/views/ticket_histories/new.html.haml
- model_class = TicketHistory
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/ticket_histories/show.html.haml
- model_class = TicketHistory
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:staff_id) + ':'
  %br
  = @ticket_history.staff_id
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @ticket_history.state
%p
  %strong= model_class.human_attribute_name(:resolution) + ':'
  %br
  = @ticket_history.resolution

.form-actions
  = link_to t('.back', default: t("helpers.links.back")), ticket_histories_path, class: 'btn'
  = link_to t('.edit', default: t("helpers.links.edit")), edit_ticket_history_path(@ticket_history), class: 'btn'
  = link_to t('.destroy', default: t("helpers.links.destroy")), ticket_history_path(@ticket_history), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'