config/routes.rb
XTick::Application.routes.draw do

  root 'tickets#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :staffs, except: [:destroy]

  post '/', to: 'search#search'

  resources :tickets, except: [:show] do
    resources :ticket_histories, except: [:show, :destroy]
  end

  get 'ticket/:customer_link', to: 'ticket_histories#customer_link',  as: 'customer_link'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  belongs_to :customer

  accepts_nested_attributes_for :customer

  has_many :ticket_histories

  validates :subject, :body, :state, :link, presence: true
  validates :subject, length: { minimum: 3,  maximum: 50 }
  validates :body, length: { minimum: 1, maximum: 250 }

  scope :created, -> { where(state: State::hash_values[:waiting_for_staff]) }
  scope :open, -> { where(state: State::hash_values[:waiting_for_customer]) }
  scope :hold, -> { where(state: State::hash_values[:on_hold]) }
  scope :closed, -> { where(state: [State::hash_values[:completed], State::hash_values[:canceled]]) }

  module State

    def self.hash_values
      {waiting_for_staff: 'Waiting for staff',
       waiting_for_customer: 'Waiting for customer',
       on_hold: 'On hold',
       canceled: 'Canceled',
       completed: 'Completed'}
    end

  end


  def self.search(text)
    tickets=Ticket.arel_table
    subject_matches = match_search_params(tickets, :subject, text)
    body_matches = match_search_params(tickets, :body, text)
    link_matches = match_search_params(tickets, :link, text)
    Ticket.where(body_matches.or(link_matches.or(subject_matches)))
  end

  def init_before_create
    init_state
    generate_unique_customer_link
  end

  def self.get_by_unique_customer_link(link)
    Ticket.where(link: link).first
  end

  def auto_set_email_address(user)
    email = user.present? ? user.email : ''
    self.customer = Customer.new(email: email)
  end

  private
  def self.match_search_params(arel_table, column, search)
    arel_table[column].matches("%#{search}%")
  end

  def init_state
    self.state = State.hash_values[:waiting_for_staff]
  end

  def generate_unique_customer_link
    self.link = generate_code
  end

  def generate_code
    value = ''
    3.times { value << (65 + rand(25)).chr }
    value << '-'
    6.times { value << (48+ rand(10)).chr }
    generate_code if Ticket.where(link: value).length != 0
    value
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:new, :create, :index]

  def index
  end

  def new
    @ticket = Ticket.new
    @ticket.auto_set_email_address current_user
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.init_before_create
    XTickMailer.ticket_created(@ticket).deliver
    return redirect_to tickets_url, notice: 'Ticket was successfully created. Check your email.' if @ticket.save
    render action: :new
  end

  def update
    return redirect_to tickets_url notice: 'Ticket was successfully updated.' if @ticket.update(ticket_params)
    render action: :edit
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:subject, :body, customer_attributes: [:name, :email])
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_customer_fields.html.haml
.control-group
  = f.label :name, class: 'control-label'
  .controls
    = f.text_field :name, class: 'text_field'
.control-group
  = f.label :email, class: 'control-label'
  .controls
    = f.email_field :email, class: 'text_area'

app/views/tickets/_form.html.haml
= form_for @ticket, html: { class: 'form-horizontal' } do |f|
  .control-group
    = f.label :subject, class: 'control-label'
    .controls
      = f.text_field :subject, class: 'text_field'
  .control-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_area :body, class: 'text_area'
  .control-group
    = f.fields_for :customer do |builder|
      = render 'customer_fields', :f => builder

  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), tickets_path, class: 'btn btn-warning'

app/views/tickets/_tab_ticket_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:customer)
      %th= model_class.human_attribute_name(:link)
      %th= model_class.human_attribute_name(:subject)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', default: t('helpers.actions')
  %tbody
    - tickets.each do |ticket|
      %tr
        %td
          %span.label.label-success
            = ticket.customer.email
        %td= ticket.link
        %td= ticket.subject
        %td= ticket.body
        %td
          %span.label.label-info
            = ticket.state
        %td=l ticket.created_at
        %td
          = link_to t('.history', default: t('helpers.links.history')), ticket_ticket_histories_path(ticket), class: 'btn btn-success'
          = link_to t('.process', default: t('helpers.links.process')), new_ticket_ticket_history_path(ticket), class: 'btn btn-warning'
          = link_to t('.edit', default: t('helpers.links.edit')), edit_ticket_path(ticket), class: 'btn btn-primary'
          = link_to t('.destroy', default: t('helpers.links.destroy')), ticket_path(ticket), method: :delete, data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) }, class: 'btn btn-danger'

app/views/tickets/edit.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/tickets/index.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize

- if user_signed_in_and_approved?
  .dashboard
    %ul.nav.nav-tabs
      %li.active
        %a{'data-target' => '#new', 'data-toggle' => 'tab', href: '#new_tickets'} New unassigned tickets
      %li
        %a{'data-target' => '#open', 'data-toggle' => 'tab', href: '#open_tickets'} Open Tickets
      %li
        %a{'data-target' => '#hold', 'data-toggle' => 'tab', href: '#hold_tickets'} On hold ticket
      %li
        %a{'data-target' => '#closed', 'data-toggle' => 'tab', href: '#closed_tickets'} Closed Tickets
      %li
        %a{'data-target' => '#searched', 'data-toggle' => 'tab', href: '#searched_tickets'} Searched
    .tab-content
      #new.tab-pane.active
        = render partial: 'tickets/tab_ticket_table', locals: { tickets: Ticket.created, model_class: model_class }
      #open.tab-pane
        = render partial: 'tickets/tab_ticket_table', locals: { tickets: Ticket.open, model_class: model_class }
      #hold.tab-pane
        = render partial: 'tickets/tab_ticket_table', locals: { tickets: Ticket.hold, model_class: model_class }
      #closed.tab-pane
        = render partial: 'tickets/tab_ticket_table', locals: { tickets: Ticket.closed, model_class: model_class }
      #searched.tab-pane
        = render partial: 'tickets/tab_ticket_table', locals: { tickets: @tickets ||= [], model_class: model_class }

For creation new ticket press button
= link_to t('.new', default: t('helpers.links.new')), new_ticket_path, class: 'btn btn-primary'

app/views/tickets/new.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: 'form'

app/views/tickets/show.html.haml
- model_class = Ticket
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:subject) + ':'
  %br
  = @ticket.subject
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @ticket.body
%p
  %strong= 'Send by :'
  %br
  = @ticket.customer.name + '; email:' + @ticket.customer.email


.form-actions
  = link_to t('.back', default: t('helpers.links.back')), tickets_path, class: 'btn btn-success'